In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[4, 10]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[16, 5], [4, 10], [1, 17], [28, 19, 25], [7, 23, 18], [18, 5], [7, 23, 17], [9, 1], [9, 1], [17, 19]]


In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[16  5  0  0]
 [ 4 10  0  0]
 [ 1 17  0  0]
 [28 19 25  0]
 [ 7 23 18  0]
 [18  5  0  0]
 [ 7 23 17  0]
 [ 9  1  0  0]
 [ 9  1  0  0]
 [17 19  0  0]]


In [5]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [6]:
X = padded_reviews
y = sentiment

In [7]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171 (684.00 Byte)
Trainable params: 171 (684.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [8]:
model.fit(X, y, epochs=50, verbose=0)

In [9]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 39ms/step - loss: 0.6451 - accuracy: 0.9000


0.8999999761581421

In [10]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [11]:
weights[13]

array([-0.02596026, -0.02076313, -0.02179059, -0.01958493,  0.01597242],
      dtype=float32)

In [12]:
weights[4]

array([ 0.08692007, -0.05816474, -0.00376143,  0.07982446,  0.08229382],
      dtype=float32)

In [13]:
weights[16]

array([ 0.06576145, -0.02635424, -0.03184253,  0.04074125,  0.02300682],
      dtype=float32)